rules = [OrganizeImports]

OrganizeImports {
  targetDialect = Scala3
  blankLines = Manual
  coalesceToWildcardImportThreshold = 2
  expandRelative = true
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = AggressiveMerge
  groups = [
    "drift"
    "---"
    "java"
    "scala"
    "---"
    "*"
  ]
  importSelectorsOrder = SymbolsFirst
  importsOrder = SymbolsFirst
  preset = DEFAULT
  removeUnused = false
}
