package drift.runner.native

import java.lang.foreign.*
import java.lang.foreign.ValueLayout.*
import java.lang.invoke.MethodHandle
import java.nio.file.*

final class HipException(val call: String, val code: Int, message: String)
    extends RuntimeException(s"$call failed with HIP error $code: $message")

/** Grid and block sizes of a kernel launch. */
final case class Dim3(x: Int, y: Int, z: Int)

object Dim3 {
  def apply(x: Int): Dim3 = Dim3(x, 1, 1)
}

/** One value passed to a kernel, typed as the kernel's C signature declares it.
  */
enum KernelArgument {
  case Pointer(value: MemorySegment)
  case I32(value: Int)
  case I64(value: Long)
  case F32(value: Float)

  /** A C struct passed by value, its bytes laid out as the kernel declares. */
  case Struct(bytes: MemorySegment)
}

/** A kernel entry point inside a loaded code object. */
final class KernelFunction(val name: String, val handle: MemorySegment)

/** The HIP runtime of one TheRock tree, called through FFM.
  *
  * The bindings are written by hand, not generated by jextract: the runner uses
  * a few dozen functions, and a generated binding of the HIP headers is
  * thousands of lines that would have to be regenerated for every TheRock
  * pairing. Each binding repeats the C signature of `hip_runtime_api.h`.
  *
  * Device pointers are zero-length `MemorySegment`s: only their address is
  * meaningful, the host must never dereference them. HIP state is per process,
  * so a process holds one of these.
  */
final class HipRuntime(val rocmRoot: Path) {

  import HipRuntime.*

  private val linker = Linker.nativeLinker()
  private val library = {
    val path = rocmRoot.resolve("lib/libamdhip64.so")
    if (!Files.isRegularFile(path))
      throw new IllegalStateException(s"no HIP runtime at $path")
    SymbolLookup.libraryLookup(path, Arena.global())
  }

  private def bind(name: String, arguments: MemoryLayout*): MethodHandle =
    bindReturning(name, JAVA_INT, arguments*)

  private def bindReturning(
      name: String,
      result: MemoryLayout,
      arguments: MemoryLayout*
  ): MethodHandle =
    linker.downcallHandle(
      library
        .find(name)
        .orElseThrow(() =>
          new IllegalStateException(s"$name is not in libamdhip64")
        ),
      FunctionDescriptor.of(result, arguments*)
    )

  private val hipInit = bind("hipInit", JAVA_INT)
  private val hipSetDevice = bind("hipSetDevice", JAVA_INT)
  private val hipSetDeviceFlags = bind("hipSetDeviceFlags", JAVA_INT)
  private val hipDeviceGetName =
    bind("hipDeviceGetName", ADDRESS, JAVA_INT, JAVA_INT)
  private val hipDeviceSynchronize = bind("hipDeviceSynchronize")
  private val hipMemGetInfo = bind("hipMemGetInfo", ADDRESS, ADDRESS)
  private val hipGetErrorString =
    bindReturning("hipGetErrorString", ADDRESS, JAVA_INT)
  private val hipMalloc = bind("hipMalloc", ADDRESS, JAVA_LONG)
  private val hipFree = bind("hipFree", ADDRESS)
  private val hipMemset = bind("hipMemset", ADDRESS, JAVA_INT, JAVA_LONG)
  private val hipMemcpy =
    bind("hipMemcpy", ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT)
  private val hipMemcpyAsync =
    bind("hipMemcpyAsync", ADDRESS, ADDRESS, JAVA_LONG, JAVA_INT, ADDRESS)
  private val hipHostRegister =
    bind("hipHostRegister", ADDRESS, JAVA_LONG, JAVA_INT)
  private val hipHostUnregister = bind("hipHostUnregister", ADDRESS)
  private val hipHostGetDevicePointer =
    bind("hipHostGetDevicePointer", ADDRESS, ADDRESS, JAVA_INT)
  private val hipStreamCreate = bind("hipStreamCreate", ADDRESS)
  private val hipStreamDestroy = bind("hipStreamDestroy", ADDRESS)
  private val hipStreamSynchronize = bind("hipStreamSynchronize", ADDRESS)
  private val hipEventCreate = bind("hipEventCreate", ADDRESS)
  private val hipEventDestroy = bind("hipEventDestroy", ADDRESS)
  private val hipEventRecord = bind("hipEventRecord", ADDRESS, ADDRESS)
  private val hipEventSynchronize = bind("hipEventSynchronize", ADDRESS)
  private val hipEventElapsedTime =
    bind("hipEventElapsedTime", ADDRESS, ADDRESS, ADDRESS)
  private val hipModuleLoadData = bind("hipModuleLoadData", ADDRESS, ADDRESS)
  private val hipModuleUnload = bind("hipModuleUnload", ADDRESS)
  private val hipModuleGetFunction =
    bind("hipModuleGetFunction", ADDRESS, ADDRESS, ADDRESS)
  private val hipModuleLaunchKernel = bind(
    "hipModuleLaunchKernel",
    ADDRESS,
    JAVA_INT,
    JAVA_INT,
    JAVA_INT,
    JAVA_INT,
    JAVA_INT,
    JAVA_INT,
    JAVA_INT,
    ADDRESS,
    ADDRESS,
    ADDRESS
  )

  /** `call` is by name: a launch names its kernel only when it fails. */
  private def check(call: => String, code: Int): Unit =
    if (code != 0) throw new HipException(call, code, errorString(code))

  private def errorString(code: Int): String = {
    val text = (hipGetErrorString.invokeExact(code): MemorySegment)
    if (text == MemorySegment.NULL) "unknown"
    else text.reinterpret(Long.MaxValue).getString(0)
  }

  /** Runs `body` with a confined arena for out-parameters. */
  private def withArena[A](body: Arena => A): A = {
    val arena = Arena.ofConfined()
    try body(arena)
    finally arena.close()
  }

  /** Calls a function whose one out-parameter is a pointer, and returns it. */
  private def pointerOut(call: String)(
      invoke: MemorySegment => Int
  ): MemorySegment =
    withArena { arena =>
      val slot = arena.allocate(ADDRESS)
      check(call, invoke(slot))
      slot.get(ADDRESS, 0)
    }

  check("hipInit", (hipInit.invokeExact(0): Int))
  check("hipSetDevice", (hipSetDevice.invokeExact(0): Int))

  // How a call that waits for the GPU waits (bug 38). HIP spins a core by
  // default; asleep until the GPU is done, a Qwen Image 2.1 tile took the same
  // 115.3 s and 3.7 s of CPU instead of 115.3 (yielding spun as much). So the
  // runner blocks, unless `DRIFT_HIP_SCHEDULE` asks for `spin` or `yield`.
  check(
    "hipSetDeviceFlags",
    (hipSetDeviceFlags.invokeExact(
      sys.env.get("DRIFT_HIP_SCHEDULE").map(_.toLowerCase) match {
        case Some("spin")  => HipRuntime.ScheduleSpin
        case Some("yield") => HipRuntime.ScheduleYield
        case _             => HipRuntime.ScheduleBlockingSync
      }
    ): Int)
  )

  def deviceName: String = withArena { arena =>
    val buffer = arena.allocate(256)
    check(
      "hipDeviceGetName",
      (hipDeviceGetName.invokeExact(buffer, 256, 0): Int)
    )
    buffer.getString(0)
  }

  /** Free and total device memory, in bytes. */
  def memoryInfo: (Long, Long) = withArena { arena =>
    val free = arena.allocate(JAVA_LONG)
    val total = arena.allocate(JAVA_LONG)
    check("hipMemGetInfo", (hipMemGetInfo.invokeExact(free, total): Int))
    (free.get(JAVA_LONG, 0), total.get(JAVA_LONG, 0))
  }

  def synchronize(): Unit =
    check("hipDeviceSynchronize", (hipDeviceSynchronize.invokeExact(): Int))

  def allocate(bytes: Long): MemorySegment =
    pointerOut("hipMalloc")(slot => (hipMalloc.invokeExact(slot, bytes): Int))

  def zero(pointer: MemorySegment, bytes: Long): Unit =
    check("hipMemset", (hipMemset.invokeExact(pointer, 0, bytes): Int))

  def free(pointer: MemorySegment): Unit =
    check("hipFree", (hipFree.invokeExact(pointer): Int))

  /** A blocking copy; HIP works out the direction from the two addresses. */
  def copy(target: MemorySegment, source: MemorySegment, bytes: Long): Unit =
    check(
      "hipMemcpy",
      (hipMemcpy.invokeExact(target, source, bytes, MemcpyDefault): Int)
    )

  /** A copy queued on the default stream, after the kernels before it. */
  def copyAsync(
      target: MemorySegment,
      source: MemorySegment,
      bytes: Long
  ): Unit =
    check(
      "hipMemcpyAsync",
      (hipMemcpyAsync.invokeExact(
        target,
        source,
        bytes,
        MemcpyDefault,
        MemorySegment.NULL
      ): Int)
    )

  /** Pins host memory and maps it for the GPU; returns the device's address for
    * it. The segment must stay alive until `unregister`.
    */
  def register(host: MemorySegment, flags: Int): MemorySegment = {
    // The driver refuses once the memory it may pin is spoken for, which is
    // what a second loaded model does: said here, the HIP error says nothing.
    val code = (hipHostRegister.invokeExact(host, host.byteSize(), flags): Int)
    if (code != 0)
      throw new HipException(
        "hipHostRegister",
        code,
        f"${errorString(code)} — ${host.byteSize() / 1e9}%.1f GB could not be pinned: the memory is probably full, stop any other loaded model"
      )
    pointerOut("hipHostGetDevicePointer")(slot =>
      (hipHostGetDevicePointer.invokeExact(slot, host, 0): Int)
    )
  }

  def unregister(host: MemorySegment): Unit =
    check("hipHostUnregister", (hipHostUnregister.invokeExact(host): Int))

  def createStream(): MemorySegment =
    pointerOut("hipStreamCreate")(slot =>
      (hipStreamCreate.invokeExact(slot): Int)
    )

  def destroyStream(stream: MemorySegment): Unit =
    check("hipStreamDestroy", (hipStreamDestroy.invokeExact(stream): Int))

  def synchronize(stream: MemorySegment): Unit =
    check(
      "hipStreamSynchronize",
      (hipStreamSynchronize.invokeExact(stream): Int)
    )

  def createEvent(): MemorySegment =
    pointerOut("hipEventCreate")(slot =>
      (hipEventCreate.invokeExact(slot): Int)
    )

  def destroyEvent(event: MemorySegment): Unit =
    check("hipEventDestroy", (hipEventDestroy.invokeExact(event): Int))

  def record(event: MemorySegment, stream: MemorySegment): Unit =
    check("hipEventRecord", (hipEventRecord.invokeExact(event, stream): Int))

  /** Milliseconds between two recorded events, once `end` has completed. */
  def elapsedMilliseconds(start: MemorySegment, end: MemorySegment): Float = {
    check("hipEventSynchronize", (hipEventSynchronize.invokeExact(end): Int))
    withArena { arena =>
      val milliseconds = arena.allocate(JAVA_FLOAT)
      check(
        "hipEventElapsedTime",
        (hipEventElapsedTime.invokeExact(milliseconds, start, end): Int)
      )
      milliseconds.get(JAVA_FLOAT, 0)
    }
  }

  def loadModule(image: MemorySegment): MemorySegment =
    pointerOut("hipModuleLoadData")(slot =>
      (hipModuleLoadData.invokeExact(slot, image): Int)
    )

  def unloadModule(module: MemorySegment): Unit =
    check("hipModuleUnload", (hipModuleUnload.invokeExact(module): Int))

  def function(module: MemorySegment, name: String): KernelFunction =
    withArena { arena =>
      val handle = pointerOut(s"hipModuleGetFunction($name)")(slot =>
        (hipModuleGetFunction.invokeExact(
          slot,
          module,
          arena.allocateFrom(name)
        ): Int)
      )
      new KernelFunction(name, handle)
    }

  /** One buffer for every launch's arguments: `hipModuleLaunchKernel` copies
    * them before it returns, so the next launch may overwrite them. A decode
    * step launches hundreds of kernels; an arena per launch cost more than the
    * launch.
    */
  private val launchBuffer = Arena.ofShared().allocate(8192, 16)

  /** Launches a kernel: each argument is written into the launch buffer, 8-byte
    * aligned, and the kernel gets an array of pointers to them, as
    * `hipModuleLaunchKernel` expects.
    */
  def launch(
      function: KernelFunction,
      grid: Dim3,
      block: Dim3,
      sharedBytes: Int,
      stream: MemorySegment,
      arguments: KernelArgument*
  ): Unit = launchBuffer.synchronized {
    val tracedFrom = if (HipRuntime.Trace.on) System.nanoTime() else 0L
    val parameters = launchBuffer.asSlice(0, 8L * arguments.size)
    var at = 8L * 64 // room for 64 pointers, then the values
    arguments.zipWithIndex.foreach { (argument, index) =>
      val value = launchBuffer.asSlice(at)
      argument match {
        case KernelArgument.Pointer(pointer) =>
          value.set(ADDRESS, 0, pointer)
          at += 8
        case KernelArgument.I32(number) =>
          value.set(JAVA_INT, 0, number)
          at += 8
        case KernelArgument.I64(number) =>
          value.set(JAVA_LONG, 0, number)
          at += 8
        case KernelArgument.F32(number) =>
          value.set(JAVA_FLOAT, 0, number)
          at += 8
        case KernelArgument.Struct(bytes) =>
          MemorySegment.copy(bytes, 0, value, 0, bytes.byteSize())
          at += (bytes.byteSize() + 7) / 8 * 8
      }
      parameters.setAtIndex(ADDRESS, index.toLong, value)
    }
    check(
      s"hipModuleLaunchKernel(${function.name})",
      (hipModuleLaunchKernel.invokeExact(
        function.handle,
        grid.x,
        grid.y,
        grid.z,
        block.x,
        block.y,
        block.z,
        sharedBytes,
        stream,
        parameters,
        MemorySegment.NULL
      ): Int)
    )
    if (HipRuntime.Trace.on) {
      // the kernel's own time: nothing else is queued once the last one is in
      synchronize()
      HipRuntime.Trace.record(function.name, System.nanoTime() - tracedFrom)
    }
  }
}

object HipRuntime {

  /** `hipMemcpyDefault`: the direction is inferred from the addresses. */
  val MemcpyDefault = 4

  /** `hipSetDeviceFlags`: how a waiting call waits — spinning, yielding the
    * core between polls, or asleep until the GPU is done.
    */
  val ScheduleSpin = 1
  val ScheduleYield = 2
  val ScheduleBlockingSync = 4

  /** `DRIFT_HIP_TRACE=1`: every kernel waited for as it is launched and timed
    * by name, and the table printed when the process ends — which kernels are
    * long enough to keep the desktop's frames waiting (bug 38), and where a
    * model's time goes. It slows a run; it is for measuring one.
    */
  object Trace {
    val on: Boolean = sys.env.get("DRIFT_HIP_TRACE").exists(_.nonEmpty)
    // name → (launches, total ns, longest ns)
    private val times =
      scala.collection.mutable.Map.empty[String, (Long, Long, Long)]

    def record(name: String, nanos: Long): Unit = times.synchronized {
      val (count, total, longest) = times.getOrElse(name, (0L, 0L, 0L))
      times(name) = (count + 1, total + nanos, longest.max(nanos))
    }

    if (on)
      Runtime.getRuntime.addShutdownHook(
        new Thread(() =>
          times.synchronized {
            println("kernel, launches, total s, mean ms, longest ms")
            times.toSeq.sortBy(-_._2._2).foreach {
              case (name, (count, total, longest)) =>
                println(
                  f"$name, $count, ${total / 1e9}%.2f, ${total / 1e6 / count}%.2f, ${longest / 1e6}%.1f"
                )
            }
          }
        )
      )
  }

  /** `hipHostRegisterMapped`: map the pinned memory into the device. */
  val RegisterMapped = 0x2

  /** `hipHostRegisterReadOnly`: the GPU only reads it (a read-only mapping). */
  val RegisterReadOnly = 0x8

  /** The runtime of the tree `DRIFT_ROCM_ROOT` names: drift sets it when it
    * launches the runner, the build sets it for the tests.
    */
  def fromEnvironment(env: Map[String, String] = sys.env): HipRuntime =
    env.get("DRIFT_ROCM_ROOT").map(_.trim).filter(_.nonEmpty) match {
      case Some(root) => new HipRuntime(Paths.get(root))
      case None       =>
        throw new IllegalStateException(
          "DRIFT_ROCM_ROOT is not set: it names the TheRock tree whose HIP runtime the runner loads"
        )
    }
}
